config/routes.rb
CloseOut::Application.routes.draw do

  resources :cabinets

  resources :equipmentinracks

  resources :port_mapfor3750_mes

  resources :site_reviews

  resources :radios

  resources :antennas

  match '/help', :to => 'static_pages#help'
  match '/about', :to => 'static_pages#about'
  match '/reviews', :to => 'site_reviews#index'
  match '/towers', :to => 'towers#index'
  match '/techs', :to => 'teches#index'
  match '/cabinets', :to => 'cabinets#index'
  match '/contact', :to => 'static_pages#contact'
  match '/login', :to => 'lock#login'

  resources :notes

  resources :boms

  resources :scope_of_works

  resources :posts

  resources :teches
  
  resources :sites, :has_many => [:teches, :towers, :radios, :antennas]
  
  resources :towers, :has_many => [:radios, :antennas]

  resources :radios, :has_many => :antennas

root :to => 'sites#index'

end

app/models/tech.rb
# == Schema Information
#
# Table name: teches
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  phone            :string(255)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  site_id          :integer
#  scope_of_work_id :integer
#

class Tech < ActiveRecord::Base
  attr_accessible :name, :phone, :site_id
  has_many :sites, :inverse_of => :tech
  belongs_to :site, :inverse_of => :tech
  has_many :scope_of_works, :inverse_of => :tech
  belongs_to :scope_of_work, :inverse_of => :tech
  has_many :notes, :inverse_of => :tech
  belongs_to :note, :inverse_of => :tech
end

app/controllers/teches_controller.rb
class TechesController < InheritedResources::Base
  helper_method :sort_column, :sort_direction
  
  def index
    @teches = Tech.order(sort_column + " " + sort_direction)
  end

  def show
    @tech = Tech.find(params[:id])
  end

  def new
    @tech = Tech.new
  end

  def create
    @tech = Tech.new(params[:tech])
    if @tech.save
      redirect_to @tech, :notice => "Successfully created tech."
    else
      render :action => 'new'
    end
  end

  def edit
    @tech = Tech.find(params[:id])
  end

  def update
    @tech = Tech.find(params[:id])
    if @tech.update_attributes(params[:tech])
      redirect_to @tech, :notice  => "Successfully updated tech."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @tech = Tech.find(params[:id])
    @tech.destroy
    redirect_to teches_url, :notice => "Successfully destroyed tech."
  end

  def sort_column
    Tech.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/teches_helper.rb
module TechesHelper
end

app/views/teches/_form.html.erb
<%= semantic_form_for @tech do |f| %>
	<%= f.inputs do %>
	    <%= f.input :name %><br />
	    <%= f.input :phone %><br />
	<% end %>
	<%= f.actions do %>
	    <%= f.action :submit, :as => :input, :label => "Submit" %>
	    <%= f.action :cancel, :label => "Cancel" %>
    <%end %>

<% end %>

app/views/teches/edit.html.erb
<div class="jumbotron subhead" id="overview">
  <div class="container">
    <h1>Editing <%= @tech.name %></h1>
  </div>
</div>
<div class="container">
<p id="notice"><%= notice %></p>

<%= render 'form' %>

<%= link_to 'Destroy', @tech, :method => :delete, :data => { :confirm => 'Are you sure?' } %>

app/views/teches/index.html.erb
<div class="jumbotron subhead" id="overview">
  <div class="container">
    <h1>All Techs</h1>
    <p class="lead">Select a tech for more information.</p>
  </div>
</div>
<div class="container">
<div class="page-header"><h1>Techs Table</h1></div>
<p id="notice"><%= notice %></p>
<table class="pretty table table-striped">
  <tr>
    <th><%= sortable "name" %></th>
    <th><%= sortable "phone" %></th>
    <th></th>
  </tr>

<% @teches.each do |tech| %>
  <tr>
    <td><%= link_to tech.name, tech %></td>
    <td><%= tech.phone %></td>
    <td><%= link_to 'Edit', edit_tech_path(tech) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tech', new_tech_path %>

app/views/teches/new.html.erb
<div class="jumbotron subhead" id="overview">
  <div class="container">
    <h1>All Techs</h1>
    <p class="lead">Select a tech for more information.</p>
  </div>
</div>
<div class="container">
<div class="page-header"><h1>New Tech</h1></div>
<p id="notice"><%= notice %></p>

<%= render 'form' %>

<%= link_to 'Back', teches_path %>

app/views/teches/show.html.erb
<div class="jumbotron subhead" id="overview">
  <div class="container">
    <h1><%=h @tech.name %></h1>
  </div>
</div>
<div class="container">
<p id="notice"><%= notice %></p>
 
<p>
  <b>Phone:</b>
  <%=h @tech.phone %>
</p>
 
<p>
  <b>Sites:</b>
     <ul>
     <% @tech.sites.each do |site| %>
        <li><%= link_to site.name, site %></li>
  	 <% end %>
  	 </ul>
    <%= link_to "Create new site", new_site_path %>
</p>

<%= link_to 'Edit', edit_tech_path(@tech) %> |
<%= link_to 'Back', teches_path %>