config/routes.rb
CloseOut::Application.routes.draw do

  resources :cabinets

  resources :equipmentinracks

  resources :port_mapfor3750_mes

  resources :site_reviews

  resources :radios

  resources :antennas

  match '/help', :to => 'static_pages#help'
  match '/about', :to => 'static_pages#about'
  match '/reviews', :to => 'site_reviews#index'
  match '/towers', :to => 'towers#index'
  match '/techs', :to => 'teches#index'
  match '/cabinets', :to => 'cabinets#index'
  match '/contact', :to => 'static_pages#contact'
  match '/login', :to => 'lock#login'

  resources :notes

  resources :boms

  resources :scope_of_works

  resources :posts

  resources :teches
  
  resources :sites, :has_many => [:teches, :towers, :radios, :antennas]
  
  resources :towers, :has_many => [:radios, :antennas]

  resources :radios, :has_many => :antennas

root :to => 'sites#index'

end

app/models/tower.rb
# == Schema Information
#
# Table name: towers
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  numbeant   :integer
#  numbnewant :integer
#  oldcables  :text
#  newcables  :text
#  site_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tower < ActiveRecord::Base
  attr_accessible :name, :newcables, :numbeant, :numbnewant, :oldcables, :site_id
  
  has_many :radios, :inverse_of => :tower
  belongs_to :radio, :inverse_of => :towers

  belongs_to :site, :inverse_of => :towers
  has_many :sites, :inverse_of => :tower

  has_many :antennas, :inverse_of => :tower
  belongs_to :antenna, :inverse_of => :tower
end

app/controllers/towers_controller.rb
class TowersController < InheritedResources::Base
end

app/helpers/towers_helper.rb
module TowersHelper
end

app/views/towers/_form.html.erb
<%= semantic_form_for @tower do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :numbeant, :label => "Existing Antennas" %>
    <%= f.input :numbnewant, :label => "New Antennas Installed"  %>
    <%= f.input :oldcables, :label => "Number and Type of Old Cables&nbsp;Removed"  %>
    <%= f.input :newcables, :label => "Number and Type of New Cables&nbsp;Installed"  %>
    <%= f.input :site_id, :as => :select, :collection => Site.all, :label_method => :format_name, :value_method => :id %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/towers/edit.html.erb
<div class="container">
<h1>Editing tower</h1>

<%= render 'form' %>

<%= link_to 'Show', @tower %> |
<%= link_to 'Back', towers_path %> |
<%= link_to 'Destroy', @tower, :method => :delete, :data => { :confirm => 'Are you sure?' } %>

app/views/towers/index.html.erb
<div class="jumbotron subhead" id="overview">
  <div class="container">
    <h1>All Towers</h1>
    <p class="lead">Select a tower for more information.</p>
  </div>
</div>
<div class="container">
<div class="page-header"><h1>Towers Table</h1></div>
<table class="pretty table table-striped">
  <tr>
    <th>Name</th>
    <th>Site</th>
    <th></th>
  </tr>

<% @towers.each do |tower| %>
  <tr>
    <td><%= link_to tower.name, tower %></td>
    <td><%= link_to tower.site.name, tower.site %></td>
    <td><%= link_to 'Edit', edit_tower_path(tower) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tower', new_tower_path %>

app/views/towers/new.html.erb
<div class="container">
<h1>New tower</h1>

<%= render 'form' %>

<%= link_to 'Back', towers_path %>

app/views/towers/show.html.erb
<div class="jumbotron subhead" id="overview">
  <div class="container">
    <h1><%= @tower.name %></h1>
  </div>
</div><div class="container">
<p id="notice"><%= notice %></p>
<div class="container">
<div class="page-header">
<h1>Site: <%= link_to @tower.site.name, @tower.site %></h2>
  <p class="lead">Tech: <%= link_to @tower.site.tech.name, @tower.site.tech %></p>
</div>

<h2>Radios</h2>
<table class="pretty table table-striped">
  <tr>
    <th>Name</th>
    <th>Desc</th>
    <th></th>
  </tr>

<% for radio in @tower.radios %>
  <tr>
    <td><%= link_to radio.name, radio %></td>
    <td><%= radio.desc %></td>
  </tr>
<% end %>
</table>
<p><i class="icon-file"></i> <%= link_to "Create New Radio", new_radio_path %></p>

<h2>Antennas</h2>
<table class="pretty table table-striped">
  <tr>
    <th>Antenna</th>
    <th>On Radio</th>
    <th>Description</th>
    <th>Antenna Type</th>
  </tr>
<% for antenna in @tower.antennas %>
  <tr>
    <td><%= link_to antenna.antenna, antenna %></td>
    <td><%= link_to antenna.radio.name, antenna.radio %></td>
    <td><%= antenna.desc %></td>
    <td><%= antenna.antennatype %></td>
  </tr>
<% end %>
</table>
<p><i class="icon-file"></i> <%= link_to "Create New Antenna", new_antenna_path %></p>
  <h3>Number of Existing Antennas</h3>
  <p><%= @tower.numbeant %></p>
  <h3>Number of New Antennas Installed</h3>
  <p><%= @tower.numbnewant %></p>

<h2>Cables</h2>
  <h3>Number/Type of Old Cables</h3>
  <p><%= @tower.oldcables %></p>
  <h3>Number/Type of New Cables</h3>
  <p><%= @tower.newcables %></p>

<%= link_to 'Edit', edit_tower_path(@tower) %> |
<%= link_to 'Back', towers_path %>