config/routes.rb
CloseOut::Application.routes.draw do

  resources :cabinets

  resources :equipmentinracks

  resources :port_mapfor3750_mes

  resources :site_reviews

  resources :radios

  resources :antennas

  match '/help', :to => 'static_pages#help'
  match '/about', :to => 'static_pages#about'
  match '/reviews', :to => 'site_reviews#index'
  match '/towers', :to => 'towers#index'
  match '/techs', :to => 'teches#index'
  match '/cabinets', :to => 'cabinets#index'
  match '/contact', :to => 'static_pages#contact'
  match '/login', :to => 'lock#login'

  resources :notes

  resources :boms

  resources :scope_of_works

  resources :posts

  resources :teches
  
  resources :sites, :has_many => [:teches, :towers, :radios, :antennas]
  
  resources :towers, :has_many => [:radios, :antennas]

  resources :radios, :has_many => :antennas

root :to => 'sites#index'

end

app/models/radio.rb
# == Schema Information
#
# Table name: radios
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  desc       :text
#  tower_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Radio < ActiveRecord::Base
  attr_accessible :desc, :name, :tower_id
  
  belongs_to :tower, :inverse_of => :radios
  belongs_to :site, :inverse_of => :radios
  
  has_many :sites, :inverse_of => :radio
  has_many :antennas, :inverse_of => :radio
  has_many :towers, :inverse_of => :radio
end

app/controllers/radios_controller.rb
class RadiosController < InheritedResources::Base
	@radio = Radio.new
end

app/helpers/radios_helper.rb
module RadiosHelper
end

app/views/radios/_form.html.erb
<%= semantic_form_for @radio do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :desc %>
    <%= f.input :tower_id, :as => :select, :collection => Tower.all, :label_method => :format_name, :value_method => :id %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/radios/edit.html.erb
<div class="container">
<h1>Editing radio</h1>

<%= render 'form' %>

<%= link_to 'Show', @radio %> |
<%= link_to 'Back', radios_path %>

app/views/radios/index.html.erb
<div class="container">
<h1>Listing radios</h1>

<table class="pretty table table-striped">
  <tr>
    <th>Name</th>
    <th>Desc</th>
    <th>Tower</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @radios.each do |radio| %>
  <tr>
    <td><%= radio.name %></td>
    <td><%= radio.desc %></td>
    <td><%= radio.tower_id %></td>
    <td><%= link_to 'Show', radio %></td>
    <td><%= link_to 'Edit', edit_radio_path(radio) %></td>
    <td><%= link_to 'Destroy', radio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Radio', new_radio_path %>

app/views/radios/new.html.erb
<div class="container">
<h1>New radio</h1>

<%= render 'form' %>

<%= link_to 'Back', radios_path %>

app/views/radios/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @radio.name %>
</p>

<p>
  <b>Desc:</b>
  <%= @radio.desc %>
</p>

<p>
  <b>Tower:</b>
  <%= @radio.tower.name %>
</p>

<table class="pretty table table-striped">
  <tr>
    <th>Radio</th>
    <th>Desc</th>
    <th>Antenna</th>
    <th>Azimuth</th>
    <th>Elevation</th>
    <th>Frequencytx</th>
    <th>Frequencyrx</th>
    <th>Height</th>
    <th>Txpower</th>
    <th>Serialnumber</th>
    <th>Phasingcolor1</th>
    <th>Phasingcolor2</th>
    <th>Sectorsize</th>
    <th>Antennatype</th>
    <th>Dishsize</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% for antenna in @radio.antennas %>
  <tr>
    <td><%= antenna.radio_id %></td>
    <td><%= antenna.desc %></td>
    <td><%= antenna.antenna %></td>
    <td><%= antenna.azimuth %></td>
    <td><%= antenna.elevation %></td>
    <td><%= antenna.frequencytx %></td>
    <td><%= antenna.frequencyrx %></td>
    <td><%= antenna.height %></td>
    <td><%= antenna.txpower %></td>
    <td><%= antenna.serialnumber %></td>
    <td><%= antenna.phasingcolor1 %></td>
    <td><%= antenna.phasingcolor2 %></td>
    <td><%= antenna.sectorsize %></td>
    <td><%= antenna.antennatype %></td>
    <td><%= antenna.dishsize %></td>
    <td><%= link_to 'Show', antenna %></td>
    <td><%= link_to 'Edit', edit_antenna_path(antenna) %></td>
    <td><%= link_to 'Destroy', antenna, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Edit', edit_radio_path(@radio) %> |
<%= link_to 'Back', radios_path %>