config/routes.rb
CloseOut::Application.routes.draw do

  resources :cabinets

  resources :equipmentinracks

  resources :port_mapfor3750_mes

  resources :site_reviews

  resources :radios

  resources :antennas

  match '/help', :to => 'static_pages#help'
  match '/about', :to => 'static_pages#about'
  match '/reviews', :to => 'site_reviews#index'
  match '/towers', :to => 'towers#index'
  match '/techs', :to => 'teches#index'
  match '/cabinets', :to => 'cabinets#index'
  match '/contact', :to => 'static_pages#contact'
  match '/login', :to => 'lock#login'

  resources :notes

  resources :boms

  resources :scope_of_works

  resources :posts

  resources :teches
  
  resources :sites, :has_many => [:teches, :towers, :radios, :antennas]
  
  resources :towers, :has_many => [:radios, :antennas]

  resources :radios, :has_many => :antennas

root :to => 'sites#index'

end

app/models/cabinet.rb
# == Schema Information
#
# Table name: cabinets
#
#  id                                       :integer          not null, primary key
#  site_id                                  :integer
#  equipinstalledpicture                    :boolean
#  onraisedplatformpadpicture               :boolean
#  cablingfromcabinetacrossicebridgepicture :boolean
#  patchcablingpicture                      :boolean
#  labelsonequippicture                     :boolean
#  dressedcablespicture                     :boolean
#  created_at                               :datetime         not null
#  updated_at                               :datetime         not null
#

class Cabinet < ActiveRecord::Base
  attr_accessible :cablingfromcabinetacrossicebridgepicture, :name, :dressedcablespicture, :labelsonequippicture, :onraisedplatformpadpicture, :patchcablingpicture, :site_id, :equipinstalledpicture
  belongs_to :site
  has_many :equipmentinracks
  has_many :port_mapfor3750_mes
end

app/controllers/cabinets_controller.rb
class CabinetsController < InheritedResources::Base
end

app/helpers/cabinets_helper.rb
module CabinetsHelper
end

app/views/cabinets/_form.html.erb
<%= semantic_form_for @cabinet do |f| %>
  <%= f.inputs do %>
    <%= f.input :site_id, :as => :select, :collection => Site.all, :label_method => :format_name, :value_method => :id %>
    <%= f.input :name %>
    <li class="input optional"><h3>Picture Checklist</h3>
    <p><i class="icon-question-sign"></i> <em>Post/Find Pictures on Each Site's Page</em></p></li>
    <%= f.input :equipinstalledpicture, :label => "Equipment Installed in Cabinet" %>
    <%= f.input :onraisedplatformpadpicture, :label => "On Raised Platform/Pad:" %>
    <%= f.input :cablingfromcabinetacrossicebridgepicture, :label => "Cabling from Cabinet Across Ice Bridge" %>
    <%= f.input :patchcablingpicture, :label => "Patch Cabling in Cabinet" %>
    <%= f.input :labelsonequippicture, :label => "Labels on Equipment" %>
    <%= f.input :dressedcablespicture, :label => "Dressed Cables in Cabinet" %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/cabinets/edit.html.erb
<div class="container">
<h1>Editing cabinet</h1>

<%= render 'form' %>

<%= link_to 'Show', @cabinet %> |
<%= link_to 'Back', cabinets_path %>

app/views/cabinets/index.html.erb
<div class="jumbotron subhead" id="overview">
  <div class="container">
    <h1>All Cabinets</h1>
  </div>
</div>
<div class="container">
  <div class="page-header"><h1>Cabinets Table</h1></div>
<p id="notice"><%= notice %></p>

<table class="pretty table table-striped">
  <tr>
    <th>Cabinet Name</th>
    <th>Site</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cabinets.each do |cabinet| %>
  <tr>
    <td><%= link_to cabinet.name, cabinet %></td>
    <td><%= link_to cabinet.site.name, cabinet.site %></td>
    <td><%= link_to 'Show', cabinet %></td>
    <td><%= link_to 'Edit', edit_cabinet_path(cabinet) %></td>
    <td><%= link_to 'Destroy', cabinet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cabinet', new_cabinet_path %>

app/views/cabinets/new.html.erb
<div class="container">
<h1>New cabinet</h1>

<%= render 'form' %>

<%= link_to 'Back', cabinets_path %>

app/views/cabinets/show.html.erb
<div class="jumbotron subhead" id="overview">
  <div class="container">
    <h1><%= link_to @cabinet.site.name, @cabinet.site %> Cabinet</h1>
  </div>
</div>
<div class="container">
  <div class="page-header"></div>
<p id="notice"><%= notice %></p>

<h2>Equpment in Rack</h2>
<table class="pretty table table-striped">
  <tr>
    <th>Item</th>
    <th>Serial</th>
    <th></th>
  </tr>

<% for equipmentinrack in @cabinet.equipmentinracks %>
  <tr>
    <td><%= link_to equipmentinrack.item, equipmentinrack %></td>
    <td><%= equipmentinrack.serialnumber %></td>
    <td><%= link_to 'Edit', edit_equipmentinrack_path(equipmentinrack) %></td>
  </tr>
<% end %>
</table>
<p><i class="icon-file"></i> <%= link_to "Add Item", new_equipmentinrack_path %></p>

<h2>Port Map for 3750ME</h2>
<table class="pretty table table-striped">
  <tr>
    <th>3650 Port</th>
    <th>Connected Device</th>
    <th>Sw Port</th>
    <th>Patch Panel Port</th>
    <th></th>
  </tr>

<% for port_mapfor3750_me in @cabinet.port_mapfor3750_mes %>
  <tr>
    <td><%= link_to port_mapfor3750_me.port, port_mapfor3750_me %></td>
    <td><%= port_mapfor3750_me.connecteddevice %></td>
    <td><%= port_mapfor3750_me.swport %></td>
    <td><%= port_mapfor3750_me.patchpanelport %></td>
    <td><%= link_to 'Edit', edit_port_mapfor3750_me_path(port_mapfor3750_me) %></td>
  </tr>
<% end %>
</table>
<p><i class="icon-file"></i> <%= link_to "Add Port", new_port_mapfor3750_me_path %></p>

<h3>Picture Checklist</h3>
<p><i class="icon-question-sign"></i> <em>Post/Find Pictures on Each Site's Page</em></p>

<p>
  <b>Equipment Installed in Cabinet:</b>
  <%= @cabinet.equipinstalledpicture %>
</p>

<p>
  <b>On Raised Platform/Pad:</b>
  <%= @cabinet.onraisedplatformpadpicture %>
</p>

<p>
  <b>Cabling from Cabinet Across Ice Bridge:</b>
  <%= @cabinet.cablingfromcabinetacrossicebridgepicture %>
</p>

<p>
  <b>Patch Cabling in Cabinet:</b>
  <%= @cabinet.patchcablingpicture %>
</p>

<p>
  <b>Labels on Equipment:</b>
  <%= @cabinet.labelsonequippicture %>
</p>

<p>
  <b>Dressed Cables in Cabinet:</b>
  <%= @cabinet.dressedcablespicture %>
</p>

<%= link_to 'Edit', edit_cabinet_path(@cabinet) %> |
<%= link_to 'Back', cabinets_path %>